# Generated by Django 3.0.8 on 2020-08-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naverwebtoon',
            name='img',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='naverwebtoon',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='naverwebtoon',
            name='title',
            field=models.TextField(),
        ),
    ]
