# Generated by Django 2.0.2 on 2020-07-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('nick', models.CharField(max_length=30, verbose_name='닉네임')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField(blank=True, verbose_name='내용')),
                ('contact', models.EmailField(max_length=254, verbose_name='E-Mail')),
            ],
        ),
    ]
